# -----------------------
# -----    Model    -----
# -----------------------
model:
  net_depth: 4
# ------------------------------
# -----    Train Params    -----
# ------------------------------
train:
    batch_size: 4
    lr: 0.0001
    infer_every_steps: 5000 # How often to infer validation images
    n_epochs: 100 # How many training epochs
    save_every_steps: 5000 # How often to save  the model's weights
    store_images: false # Do you want to write infered images to disk
# ---------------------------
# -----    Data Conf    -----
# ---------------------------
data:
    path: "/scratch/sankarak/data/glaciers/" # Where's the data?
    num_workers: 1 # How many workers for the dataloader
    load_limit: -1 # Limit the number of samples per epoch | -1 to disable
