experiment:
    name: explore-lr-experiment
    exp_dir: $SCRATCH/glaciers/
    repeat: 1

runs:
  - sbatch:
      runtime: "00:30:00"
      message: fixed rate
      conf_name: explore-lr
    config:
      model: {} # empty dictionnary, don't change anything
      data: {}
      train:
        lr: 0.0001 # overwrite config.train.lr

  - sbatch:
      runtime: "00:30:00"
      message: some random rates
      conf_name: random-rates
    config:
      model: {}
      data:
        use_snow_i:
          sample: list
          from: [true, false]
        use_slope:
          sample: list
          from: [true, false]
        use_elev:
          sample: list
          from: [true, false]
        channels_to_inc:
          sample: subset
          base: [0, 1, 2, 3, 4]
          from: [5, 6, 7, 8, 9]

      train:
        lr:
          sample: log
          from: [-5, -2]
