data:
  borders: true
  load_limit: -1
  metadata: sat_data.csv
  original_path: /scratch/sankarak/data/glaciers/
  path: /scratch/sankarak/data/glaciers/
model:
  inchannels: 11
  net_depth: 4
  outchannels: 1
train:
  batch_size: 4
  infer_every_steps: 5000
  lr:
    from:
    - 1.0e-05
    - 0.01
    sample: uniform
  n_epochs: 100
  num_workers: 1
  save_freq: 2
  shuffle: true
  store_images: false
