# -----------------------
# -----    Model    -----
# -----------------------
model:
  net_depth: 4
# ------------------------------
# -----    Train Params    -----
# ------------------------------
train:
    batch_size: 4
    lr: 0.0001
    shuffle: true
    infer_every_steps: 5000 # How often to infer validation images
    n_epochs: 2 # How many training epochs
    save_freq: 2 # How often to save  the model's weights
    store_images: true # Do you want to write infered images to disk
    num_workers: 1 # How many workers for the dataloader
# ---------------------------
# -----    Data Conf    -----
# ---------------------------
data:
    path: "./data" # Where's the data?
    country: ["nepal"]
    year: "all"
    metadata:  "sat_data.csv"
    load_limit: -1 # Limit the number of samples per epoch | -1 to disable
    borders: false
    use_snow_i: true
    use_slope: false
    use_elev: true
    mask_used: "debris_glacier"
    channels_to_inc: [0, 1, 2, 3, 4, 6, 8, 5, 7]
    normalization_file: normalization_data.pkl

augmentation:
    vflip: 0.5 # percent of time to do vertical flip
    hflip: 0.5 # percent of time to do horizontal flip
    rotate_prop: 0.5 # perecent of time to rotate
    rotate_degree: 30 # maximum allowed rotation