# -----------------------
# -----    Model    -----
# -----------------------
model:
  net_depth: 4
# ------------------------------
# -----    Train Params    -----
# ------------------------------
train:
    batch_size: 4
    lr: 0.0001
    shuffle: true
    infer_every_steps: 5000 # How often to infer validation images
    n_epochs: 2 # How many training epochs
    save_freq: 2 # How often to save  the model's weights
    store_images: false # Do you want to write infered images to disk
    num_workers: 1 # How many workers for the dataloader
# ---------------------------
# -----    Data Conf    -----
# ---------------------------
data:
    path: "./data" # Where's the data?
    metadata:  "sat_data.csv"
    load_limit: -1 # Limit the number of samples per epoch | -1 to disable
    borders: false
    use_snow_i: true
    use_slope: true
    use_elev: true
    mask_used: "debris_glacier"
    channels_to_inc: [0, 1, 2, 3, 4]