model_opts:
  name: "UnetDropout"
  args: 
    inchannels: 12
    outchannels: 1
    net_depth: 4
    dropout: 0.2
    spatial: True
optim_opts:
  name: "Adam"
  args: 
    lr: 0.0001
metrics_opts:
  precision:
    threshold: 0.5
  IoU:
    threshold: 0.5
  pixel_acc:
    threshold: 0.5