# -----------------------
# -----    Model    -----
# -----------------------
model:
  inchannels: 11
  net_depth: 4
  outchannels: 1
# ------------------------------
# -----    Train Params    -----
# ------------------------------
train:
    batch_size: 4
    infer_every_steps: 5000 # How often to infer validation images
    lr: 0.0001
    n_epochs: 100 # How many training epochs
    num_workers: 1 # How many workers for the dataloader
    save_freq: 2 # How often to save  the model's weights
    shuffle:  true
    store_images: false # Do you want to write infered images to disk
# ---------------------------
# -----    Data Conf    -----
# ---------------------------
data:
    borders: false
    channels_to_inc: [0, 1, 2, 3, 4]
    load_limit: -1 # Limit the number of samples per epoch | -1 to disable
    metadata:  "sat_data.csv"
    path: "/mnt/krismachinesdiag/" # Where's the data?
    use_snow_i: true
