# -----------------------
# -----    Model    -----
# -----------------------
model:
  net_depth: 4
# ------------------------------
# -----    Train Params    -----
# ------------------------------
train:
    batch_size: 4
    lr: 0.0001
    shuffle:  true
    infer_every_steps: 5000 # How often to infer validation images
    n_epochs: 100 # How many training epochs
    save_freq: 2 # How often to save  the model's weights
    store_images: true # Do you want to write infered images to disk
    num_workers: 1 # How many workers for the dataloader
# ---------------------------
# -----    Data Conf    -----
# ---------------------------
data:
    path: "/scratch/shimaa/data/processed_glacier_data" # Where's the data?
    metadata:  "sat_data.csv" # meta data file name
    country: "all" # List of all countries to include. "all" to include all avilable years
                # This only affect the training data, not the validation and test
    year: "all" # List of all years to include. "all" to include all avilable years
                # This only affect the training data, not the validation and test
    load_limit: -1 # Limit the number of samples per epoch | -1 to disable
    borders: false # Whether to use the border as an extra channel
    use_snow_i: false # Whether to use snow index as an extra channel
    use_slope: false # Whether to use slope as an extra channel
    use_elev: false # Whether to use elevation as an extra channel
    mask_used: "glacier" # The labels used to predict.
                         # Options are 'glaciers' [default] for all the labels or
                         # 'debris_glaciers' for psuedo debris glaciers labels 
    channels_to_inc: [0,    # B1            0.45-0.52 μm    (blue) surface reflectance
                    1,      # B2            0.52-0.60 μm    (green) surface reflectance
                    2,      # B3            0.63-0.69 μm    (red) surface reflectance
                    3,      # B4            0.77-0.90 μm    (near infrared) surface reflectance
                    4,      # B5            1.55-1.75 μm    (shortwave infrared 1) surface reflectance
                    5,      # B6_VCID_1     10.40-12.50 μm  brightness temperature
                    6,      # B6_VCID_2     2.08-2.35 μm    (shortwave infrared 2) surface reflectance
                    7,      # B7            	    Atmospheric opacity; < 0.1 = clear; 0.1 - 0.3 = average; > 0.3 = hazy
                    8,      # B8                    Cloud quality attributes.
                    9       # BQA                   Pixel quality attributes generated from the CFMASK algorithm.
                    ] # list of all the channels to include (from 0 to 9)
    normalization_file: normalization_data.pkl # What normalization file to use


augmentation:
    augment: true # To augment or not
    vflip: 0.5 # percent of time to do vertical flip
    hflip: 0.5 # percent of time to do horizontal flip
    rotate_prop: 0.5 # perecent of time to rotate
    rotate_degree: 30 # maximum allowed rotation